# Basic
title: 
subtitle: 
description: 欢迎访问我的博客
# 头像里面的标题
avatarTitle: cheng
# 头像里面的描述
avatarDesc: python/java
url: 
# Comment
comment:
    provider: duoshuo
    duoshuo:
     short_name: strugglecheng

# Social
social:
    github: strugglecheng

baidu:
    id: 44dcd6189b9c8523c1eb96a0521fcf34 

permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #000000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green 

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}   
    - {title: 留言, description: liuyan, url: '/liuyan'}
    - {title: 关于, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

